name: Deploy JobSolution

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/job_solution:latest

      - name: Prepare deployment files
        run: |
          # Создаем временную директорию для файлов деплоя
          mkdir -p deploy_files
          
          # Копируем docker-compose.yml
          cp docker-compose.yml deploy_files/
          
          # Копируем nginx.conf если он есть
          if [ -f "nginx.conf" ]; then
            cp nginx.conf deploy_files/
          fi
          
          # Копируем скрипт для инициализации SSL-сертификатов
          if [ -f "init-letsencrypt.sh" ]; then
            cp init-letsencrypt.sh deploy_files/
            chmod +x deploy_files/init-letsencrypt.sh
            # Обновляем email в скрипте
            sed -i "s/your-real-email@example.com/${{ secrets.SSL_EMAIL }}/g" deploy_files/init-letsencrypt.sh
          fi
          
          # Создаем директории для миграций
          mkdir -p deploy_files/internal/db/migrations
          
          # Копируем файлы миграций
          cp -r internal/db/migrations/* deploy_files/internal/db/migrations/
          
          # Для проверки выводим список файлов
          echo "Файлы для деплоя:"
          ls -la deploy_files/
          ls -la deploy_files/internal/db/migrations/

      - name: Copy deployment files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          source: "deploy_files/*"
          target: "/home/${{ secrets.SERVER_USER }}/temp_deploy"
          strip_components: 1

      - name: Deploy to server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e

            cd ~
            
            # Создаём директории если они не существуют
            mkdir -p internal/db/migrations
            mkdir -p certbot/conf certbot/www
            
            # Копируем файлы из временной директории деплоя
            if [ -d ~/temp_deploy ]; then
              # Копируем docker-compose.yml и nginx.conf
              cp ~/temp_deploy/docker-compose.yml ./docker-compose.yml
              if [ -f ~/temp_deploy/nginx.conf ]; then
                cp ~/temp_deploy/nginx.conf ./nginx.conf
              fi
              
              # Копируем скрипт для SSL
              if [ -f ~/temp_deploy/init-letsencrypt.sh ]; then
                cp ~/temp_deploy/init-letsencrypt.sh ./init-letsencrypt.sh
                chmod +x ./init-letsencrypt.sh
              fi
              
              # Копируем миграции с правильными правами
              if [ -d ~/temp_deploy/internal/db/migrations ]; then
                echo "Копирование миграций..."
                sudo cp -r ~/temp_deploy/internal/db/migrations/* ./internal/db/migrations/
                # Настраиваем права доступа
                sudo chmod -R 777 ./internal/db
                sudo chown -R $(whoami):$(whoami) ./internal
              else
                echo "ПРЕДУПРЕЖДЕНИЕ: Миграции не найдены в директории temp_deploy!"
                ls -la ~/temp_deploy
              fi
              
              # Удаляем временную директорию
              rm -rf ~/temp_deploy
            else
              echo "ОШИБКА: Директория temp_deploy не найдена!"
              exit 1
            fi

            # Создание .env файла
            cat > .env <<EOL
            # Настройки сервера
            SERVER_PORT=${{ secrets.SERVER_PORT }}
            SERVER_MODE=${{ secrets.SERVER_MODE }}

            # PostgreSQL
            POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
            POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
            POSTGRES_USER=${{ secrets.POSTGRES_USER }}
            POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
            POSTGRES_DB=${{ secrets.POSTGRES_DB }}
            POSTGRES_SSLMODE=${{ secrets.POSTGRES_SSLMODE }}
            POSTGRES_MAX_OPEN_CONNS=${{ secrets.POSTGRES_MAX_OPEN_CONNS }}
            POSTGRES_MAX_IDLE_CONNS=${{ secrets.POSTGRES_MAX_IDLE_CONNS }}
            POSTGRES_CONN_MAX_LIFETIME=${{ secrets.POSTGRES_CONN_MAX_LIFETIME }}

            # JWT
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}
            JWT_REFRESH_EXPIRES_IN=${{ secrets.JWT_REFRESH_EXPIRES_IN }}

            # Безопасность
            PASSWORD_SALT=${{ secrets.PASSWORD_SALT }}

            # Лимиты запросов
            RATE_LIMIT_REQUESTS=${{ secrets.RATE_LIMIT_REQUESTS }}
            RATE_LIMIT_DURATION=${{ secrets.RATE_LIMIT_DURATION }}

            # Docker Hub
            DOCKER_USERNAME=${{ secrets.DOCKER_USERNAME }}
            EOL

            # Проверка наличия директории с миграциями
            if [ ! -d "internal/db/migrations" ] || [ -z "$(ls -A internal/db/migrations)" ]; then
              echo "ПРЕДУПРЕЖДЕНИЕ: Директория миграций пуста или не существует!"
              echo "Попытка создать структуру..."
              mkdir -p internal/db/migrations
            else
              echo "Директория миграций существует и содержит файлы:"
              ls -la internal/db/migrations
            fi

            # Принудительная остановка всех старых контейнеров
            echo "Остановка всех старых контейнеров..."
            docker-compose down || true
            
            # Проверка на наличие "зависших" контейнеров и их удаление
            if docker ps -a | grep "job_solution_"; then
              echo "Обнаружены старые контейнеры, удаляем их принудительно..."
              docker ps -a | grep "job_solution_" | awk '{print $1}' | xargs -r docker rm -f
            fi
            
            # Загрузка образов
            echo "Загрузка новых образов..."
            docker-compose pull

            # Запуск новых контейнеров
            echo "Запуск новых контейнеров..."
            docker-compose up -d

            # Настройка SSL-сертификатов, если скрипт существует и не было ранее настроенных сертификатов
            if [ -f "./init-letsencrypt.sh" ] && [ ! -d "certbot/conf/live" ]; then
              echo "Запуск настройки SSL-сертификатов..."
              ./init-letsencrypt.sh
              
              # Активация HTTPS конфигурации в nginx.conf, если сертификаты были успешно получены
              if [ -d "certbot/conf/live" ]; then
                echo "Активация HTTPS конфигурации..."
                cp nginx.conf nginx.conf.backup
                sed -i 's/# server {/server {/g' nginx.conf
                sed -i 's/# listen 443 ssl;/listen 443 ssl;/g' nginx.conf
                sed -i 's/# listen \[::]:443 ssl;/listen [::]:443 ssl;/g' nginx.conf
                sed -i 's/# server_name/server_name/g' nginx.conf
                sed -i 's/# ssl_certificate/ssl_certificate/g' nginx.conf
                sed -i 's/# ssl_certificate_key/ssl_certificate_key/g' nginx.conf
                sed -i 's/# ssl_protocols/ssl_protocols/g' nginx.conf
                sed -i 's/# ssl_prefer_server_ciphers/ssl_prefer_server_ciphers/g' nginx.conf
                sed -i 's/# ssl_ciphers/ssl_ciphers/g' nginx.conf
                sed -i 's/# ssl_session_cache/ssl_session_cache/g' nginx.conf
                sed -i 's/# ssl_session_timeout/ssl_session_timeout/g' nginx.conf
                sed -i 's/# ssl_stapling/ssl_stapling/g' nginx.conf
                sed -i 's/# ssl_stapling_verify/ssl_stapling_verify/g' nginx.conf
                sed -i 's/# root/root/g' nginx.conf
                sed -i 's/# index/index/g' nginx.conf
                sed -i 's/# gzip/gzip/g' nginx.conf
                sed -i 's/# gzip_comp_level/gzip_comp_level/g' nginx.conf
                sed -i 's/# gzip_min_length/gzip_min_length/g' nginx.conf
                sed -i 's/# gzip_proxied/gzip_proxied/g' nginx.conf
                sed -i 's/# gzip_vary/gzip_vary/g' nginx.conf
                sed -i 's/# gzip_types/gzip_types/g' nginx.conf
                sed -i 's/#         application\/javascript/        application\/javascript/g' nginx.conf
                sed -i 's/#         application\/json/        application\/json/g' nginx.conf
                sed -i 's/#         application\/xml/        application\/xml/g' nginx.conf
                sed -i 's/#         application\/xml+rss/        application\/xml+rss/g' nginx.conf
                sed -i 's/#         image\/svg+xml/        image\/svg+xml/g' nginx.conf
                sed -i 's/#         text\/css/        text\/css/g' nginx.conf
                sed -i 's/#         text\/javascript/        text\/javascript/g' nginx.conf
                sed -i 's/#         text\/plain/        text\/plain/g' nginx.conf
                sed -i 's/#         text\/xml;/        text\/xml;/g' nginx.conf
                sed -i 's/# location \/api\//location \/api\//g' nginx.conf
                sed -i 's/#         proxy_pass/        proxy_pass/g' nginx.conf
                sed -i 's/#         proxy_http_version/        proxy_http_version/g' nginx.conf
                sed -i 's/#         proxy_set_header Upgrade/        proxy_set_header Upgrade/g' nginx.conf
                sed -i 's/#         proxy_set_header Connection/        proxy_set_header Connection/g' nginx.conf
                sed -i 's/#         proxy_set_header Host/        proxy_set_header Host/g' nginx.conf
                sed -i 's/#         proxy_set_header X-Real-IP/        proxy_set_header X-Real-IP/g' nginx.conf
                sed -i 's/#         proxy_set_header X-Forwarded-For/        proxy_set_header X-Forwarded-For/g' nginx.conf
                sed -i 's/#         proxy_set_header X-Forwarded-Proto/        proxy_set_header X-Forwarded-Proto/g' nginx.conf
                sed -i 's/#         proxy_cache_bypass/        proxy_cache_bypass/g' nginx.conf
                sed -i 's/# location \//location \//g' nginx.conf
                sed -i 's/# location ~\* \\\.(?:ico|css|js|gif|jpe\?g|png|svg|woff|woff2|ttf|eot)\$/location ~* \\\.(?:ico|css|js|gif|jpe?g|png|svg|woff|woff2|ttf|eot)\$/g' nginx.conf
                sed -i 's/#         expires 30d;/        expires 30d;/g' nginx.conf
                sed -i 's/#         add_header Cache-Control/        add_header Cache-Control/g' nginx.conf
                sed -i 's/# location ~\* \\\.html\$/location ~* \\\.html\$/g' nginx.conf
                sed -i 's/#         expires -1;/        expires -1;/g' nginx.conf
                
                # Перезапуск Nginx для применения изменений
                docker-compose restart nginx
                echo "HTTPS настроен и активирован!"
              else
                echo "Не удалось активировать HTTPS - сертификаты не были получены."
              fi
            fi
            
            # Очистка неиспользуемых образов
            docker image prune -af
            
            # Отображение статуса
            echo "Статус контейнеров:"
            docker-compose ps
